import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-white/10">
          <nav className="mx-auto flex max-w-5xl items-center gap-6 p-4">
            <Link className="font-semibold" href="/">
              Leaven Church
            </Link>
            <Link href="/messages">Messages</Link>
            <Link href="/about">About</Link>
            <Link href="/donate">Donate</Link>
            <Link href="/visit">Visit</Link>
          </nav>
        </header>
        <div className="mx-auto max-w-5xl p-4">{children}</div>
      </body>
    </html>
  );
}
